version: 0.0
os: linux

files:
  - source: frontend/dist/
    destination: /var/www/a081100-mini5-AngularApp

  - source: backend/build/libs/
    destination: /home/ec2-user/backend

permissions:
  - object: /var/www/a081100-mini5-AngularApp
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory

  - object: /home/ec2-user/backend
    pattern: '**'
    mode: '0755'
    owner: ec2-user
    group: ec2-user
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300
      