version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18

  pre_build:
    commands:
      - echo "Frontend install"
      - cd $CODEBUILD_SRC_DIR/frontend || exit 1
      - npm ci
      - cd $CODEBUILD_SRC_DIR

  build:
    commands:
      - echo "Frontend build"
      - cd $CODEBUILD_SRC_DIR/frontend || exit 1
      - npm run build
      - cd $CODEBUILD_SRC_DIR

      - echo "Backend build"
      - cd $CODEBUILD_SRC_DIR/backend || exit 1
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - cd $CODEBUILD_SRC_DIR

  post_build:
    commands:
      - echo "=== build output ==="
      - ls -al $CODEBUILD_SRC_DIR
      - ls -al $CODEBUILD_SRC_DIR/backend/build/libs
      - ls -al $CODEBUILD_SRC_DIR/frontend/dist

artifacts:
  files:
    - appspec.yml
    - deploy-scripts/**/*
    - backend/build/libs/**/*
    - frontend/dist/**/*