version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli@17
      - java: corretto17
      - nodejs: 18

  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm install
      - echo "Frontend install"
      - cd frontend
      - npm ci
      - cd ..

  build:
    commands:
      - echo "Building Angular project..."
      - ng build -c production
      - echo "Build completed at $(date)"
      - echo "Frontend build"
      - cd frontend
      - npm run build
      - cd ..

      - echo "Backend build"
      - cd backend
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - cd ..

  post_build:
    commands:
      - echo "=== build output ==="
      - ls -al
      - ls -al backend/build/libs
      - ls -al frontend/dist

artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
  discard-paths: no
    - appspec.yml
    - deploy-scripts/**/*
    - backend/build/libs/**/*
    - frontend/dist/**/*