version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install Angular CLI"
      - npm install -g @angular/cli@17

  pre_build:
    commands:
      - echo "Install frontend dependencies"
      - cd $CODEBUILD_SRC_DIR/frontend || exit 1
      - npm ci
      - cd $CODEBUILD_SRC_DIR

  build:
    commands:
      - echo "Run unit tests"
      - cd $CODEBUILD_SRC_DIR/frontend || exit 1
      - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
      - cd $CODEBUILD_SRC_DIR