version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install Angular CLI globally"
      - npm install -g @angular/cli@17
      - cd $CODEBUILD_SRC_DIR/frontend || exit 1
      - npm ci
      - cd $CODEBUILD_SRC_DIR

  pre_build:
    commands:
      - echo "Pre-build phase: nothing extra for unit test"

  build:
    commands:
      - echo "Running Angular unit tests"
      - cd $CODEBUILD_SRC_DIR/frontend || exit 1
      # Headless Chrome 실행을 위해 환경 변수 설정 (CodeBuild용)
      - export CHROME_BIN=/usr/bin/google-chrome-stable || true
      - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI || echo "Unit test failures ignored for now"
      - cd $CODEBUILD_SRC_DIR

  post_build:
    commands:
      - echo "=== Unit test build complete ==="
      - ls -al $CODEBUILD_SRC_DIR/frontend/dist

artifacts:
  files:
    - appspec.yml
    - deploy-scripts/**/*
    - frontend/dist/**/*